"""add haystack fields

Revision ID: 90383adb1f54
Revises: f81840d79b8b
Create Date: 2026-05-17 18:26:54.835537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90383adb1f54'
down_revision: Union[str, Sequence[str], None] = 'f81840d79b8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('volume_id', sa.Integer(), nullable=True))
    op.add_column('files', sa.Column('offset', sa.Integer(), nullable=True))
    op.add_column('files', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'status')
    op.drop_column('files', 'offset')
    op.drop_column('files', 'volume_id')
    # ### end Alembic commands ###
