"""Add billing

Revision ID: b507fa46e25b
Revises: 5393312ff1ac
Create Date: 2026-04-19 16:18:19.597740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b507fa46e25b'
down_revision: Union[str, Sequence[str], None] = '5393312ff1ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buckets', sa.Column('current_storage_bytes', sa.Integer(), nullable=True))
    op.add_column('buckets', sa.Column('ingress_bytes', sa.Integer(), nullable=True))
    op.add_column('buckets', sa.Column('egress_bytes', sa.Integer(), nullable=True))
    op.add_column('buckets', sa.Column('internal_transfer_bytes', sa.Integer(), nullable=True))
    op.add_column('buckets', sa.Column('count_write_requests', sa.Integer(), nullable=True))
    op.add_column('buckets', sa.Column('count_read_requests', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buckets', 'count_read_requests')
    op.drop_column('buckets', 'count_write_requests')
    op.drop_column('buckets', 'internal_transfer_bytes')
    op.drop_column('buckets', 'egress_bytes')
    op.drop_column('buckets', 'ingress_bytes')
    op.drop_column('buckets', 'current_storage_bytes')
    # ### end Alembic commands ###
