"""Add QueuedMessage

Revision ID: f81840d79b8b
Revises: 9a562086267b
Create Date: 2026-04-26 13:39:52.305501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f81840d79b8b'
down_revision: Union[str, Sequence[str], None] = '9a562086267b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queued_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('payload', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_delivered', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queued_messages_topic'), 'queued_messages', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_queued_messages_topic'), table_name='queued_messages')
    op.drop_table('queued_messages')
    # ### end Alembic commands ###
